export const ADD_DAY_DATA = "ADD_DAY_DATA";
export const RESET_STATE = "RESET_STATE";
export const EDIT_DAY_DATA = "EDIT_DAY_DATA";
export const COMPLETE_TODO = "COMPLETE_TODO";
export const COMPLETE_ALL_TODOS = "COMPLETE_ALL_TODOS";
export const CLEAR_COMPLETED = "CLEAR_COMPLETED";
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";
